language: python

services:
  - docker

before_install:
  - docker build -t berndserker/ocr-api .
  
deploy:
  provider: script
  script:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin && docker push berndserker/ocr-api
  on:
    branch: master
